FROM node:18-alpine

WORKDIR /app

# Add build arguments for environment variables
ARG REACT_APP_API_URL
ENV REACT_APP_API_URL=${REACT_APP_API_URL}

COPY package.json package-lock.json ./
RUN npm install

COPY . .

# Start development server
CMD ["npm", "start"]

EXPOSE 3000